# Generated by Django 3.0.7 on 2020-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200726_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='projectLink',
            field=models.URLField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year_in_school',
            field=models.CharField(choices=[('Web Dev', 'Web Dev'), ('App Dev', 'App Dev'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Research', 'Research'), ('Database Management', 'Database Management'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=60),
        ),
    ]
