# Generated by Django 3.0.7 on 2020-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200728_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='year_in_school',
            new_name='projectCategory',
        ),
    ]
