# Generated by Django 3.0.7 on 2020-07-28 10:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200728_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectCategory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Web Dev', 'Web Dev'), ('App Dev', 'App Dev'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Research', 'Research'), ('Database Management', 'Database Management'), ('Other', 'Other')], max_length=94),
        ),
    ]
