# Generated by Django 3.0.7 on 2020-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200728_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectTeam',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(max_length=180),
        ),
    ]
