# Generated by Django 3.0.7 on 2020-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200728_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(max_length=300),
        ),
    ]
