# Generated by Django 3.0.7 on 2020-07-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200728_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectTeam',
            field=models.CharField(max_length=100),
        ),
    ]
