# Generated by Django 3.0.7 on 2020-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_placementteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementteammember',
            name='memberPicture',
            field=models.ImageField(default=' ', upload_to='images/'),
            preserve_default=False,
        ),
    ]
