# Generated by Django 3.0.7 on 2020-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_placementteammember_memberpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectTechnologies',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
